{
    'name': 'HR Employee report',
    'author': 'M.Arsalan',
    'version': '1.0.0',
    'category': '',
    'website':'',
    'sequence': -100,
    'summary': '',
    'description': """""",
    'depends': ['hr','hr_employee_customization','hr_recruitment'],
    'data': [
        'reports/hr_employee_report_view.xml', 
        'reports/hr_employee_onboarding_report_view.xml',
        'reports/hr_employee_offboarding_report_view.xml',
        'reports/hr_applicant_offer_letter.xml',
        'reports/hr_applicant_internship_offer_letter.xml',
        'reports/hr_employee_non_disclosure_agreement.xml',
        'reports/report.xml',
        'views/view_field.xml', 
    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'assets': {},
    'license': 'LGPL-3',
}